version: "3"

services:
    Server:
        image: handsonsecurity/seed-ubuntu:large
        container_name: Server
        tty: true
        cap_add:
                - ALL
        privileged: true
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.2


    User:
        image: handsonsecurity/seed-ubuntu:large
        container_name: User
        tty: true
        cap_add:
                - ALL
        privileged: true
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.3


networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24

